server:
  port: 8070
spring:
  application:
    name: mall-monitor
  security:
    user:
      name:
      password:
  boot:
    admin:
      discovery:
        ignored-services: ${spring.application.name}

