server:
  port: 8081
spring:
  application:
    name: mall-demo
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/starsmall?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password:
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.starsofocean.mallAdmin.domain
feign:
  okhttp:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 50000
        readTimeout: 50000
        loggerLevel: basic