server:
  port: 8080
spring:
  application:
    name: mall-admin
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/starsmall?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password:
  redis:
    host:
    port: 6379
    database: 0
    password:
    timeout: 5000
  cache:
    redis:
      time-to-live: 600000  #缓存过期时间
  rabbitmq:
    host:
    port: 5672
    username:
    password:
    virtual-host: /
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 10MB #限制文件上传大小为10M
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.starsofocean.mallAdmin.domain
feign:
  okhttp:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 50000
        readTimeout: 50000
        loggerLevel: basic
#feign:
#  httpclient:
#    enabled: true  #支持httpclient的开关
#    max-connections: 200  #最大连接数
#    max-connections-per-route: 50  #单个路径的最大连接数
